### ISSUE TITLE
Bugs in v 0.3.3

### ISSUE THREAD

**Issue by farhmadi** [Jeffjewett27/BoomerangFoo#1]
Hi
Ive seen two bugs in this version, first one is when u set the match length by number for example 30 it will set on short length and after u finish the match and hit rematch it will be 30. Then u change to 20 it will be 30 at first and after hitting rematch it will be 20.
Second bug is for the name of two new game modes, at first their name is ok, but after playing some matches or changing modifiers i dont know which , both their names change to free for all.

And Thanks for the mod. Its amazing

**Comment by Jeffjewett27** [comment]
Thank you for the feedback! I have identified the source of the first bug (match length is set before StartMatch). I will include this fix in v0.3.4. 

I was unable to replicate the name glitch or find any reason that would happen. If it happens again, make a note of what steps you followed to trigger it.

Glad you like the mod.

**Comment by Jeffjewett27** [comment]
A fix for the match length issue is included in [v0.3.4](https://github.com/Jeffjewett27/BoomerangFoo/releases/tag/v0.3.4).

**Comment by farhmadi** [comment]
Thank u for the fixes and updates.
Is there a way to unlock all hats in game?
Also dynamic camera option isnt showing up in modifiers

**Comment by Jeffjewett27** [comment]
Hi, I just added a bit of information about debug mode in the mod README.md. You can unlock the hats by pressing `F1` to unlock debug mode, then `H` to unlock all hats, then `Page Down` to save.

Dynamic camera option is not yet a feature ported from wq13sk's mod.
